export class NavigationConstants {
  // ========== 主导航ID ==========
  static readonly MAIN_NAVIGATION_ID: string = 'MAIN_NAVIGATION_ID';
  // ========== 子导航ID ==========
  // static readonly CHILD_NAVIGATION: string = 'childNavigation';
  // ========== 系统Navigation组件ID =========
  // static readonly SYSTEM_NAVIGATION_ID = 'SystemNavigationId';

  static readonly INIT_PAGE: string = 'pages/InitPage';
  static readonly SPLASH_PAGE: string = 'SPLASH_PAGE';
  static readonly INDEX_PAGE: string = 'INDEX_PAGE';
}