export class NavigationConstants {
  // ========== 主导航ID ==========
  static readonly MAIN_NAVIGATION_ID: string = 'MAIN_NAVIGATION_ID';
  // ========== 子导航ID ==========
  // static readonly CHILD_NAVIGATION: string = 'childNavigation';
  // ========== 系统Navigation组件ID =========
  // static readonly SYSTEM_NAVIGATION_ID = 'SystemNavigationId';

  static readonly INIT_PAGE: string = 'pages/InitPage';
  static readonly SPLASH_PAGE: string = 'SPLASH_PAGE';
  static readonly INDEX_PAGE: string = 'INDEX_PAGE';
  static readonly WEBLONGSCREENSHOT_PAGE: string = 'WEBLONGSCREENSHOT_PAGE';
  static readonly CHILDLISTENERFATHERFUNCTION_PAGE: string = 'CHILDLISTENERFATHERFUNCTION_PAGE';
  static readonly SAVEIMAGE_PAGE: string = 'SAVEIMAGE_PAGE';
  static readonly LONGLISTSCREENSHOT_PAGE: string = 'LONGLISTSCREENSHOT_PAGE';
  static readonly DOWNLOADFILE_PAGE: string = 'DOWNLOADFILE_PAGE';
  static readonly HORIZONTALLISTWITHCENTERSCOLL_PAGE: string = 'HORIZONTALLISTWITHCENTERSCOLL_PAGE';
  static readonly CUSTOMANIMATORMAIN_PAGE: string = 'CUSTOMANIMATORMAIN_PAGE';
  static readonly CUSTOMANIMATORTABSWITHSCROLL_PAGE: string = 'CUSTOMANIMATORTABSWITHSCROLL_PAGE';
  static readonly CUSTOMANIMATORTABS_PAGE: string = 'CUSTOMANIMATORTABS_PAGE';
  static readonly BINDSHEET_PAGE: string = 'BINDSHEET_PAGE';
  static readonly STAGGEREDGRID_PAGE: string = 'STAGGEREDGRID_PAGE';
  static readonly OPENCUSTOMDIALOGWITHLIST_PAGE: string = 'OPENCUSTOMDIALOGWITHLIST_PAGE';
  static readonly LISTVIEWDEMO_PAGE: string = 'LISTVIEWDEMO_PAGE';
  static readonly COLORTRANSITIONDEMO_PAGE: string = 'COLORTRANSITIONDEMO_PAGE';
  static readonly DB_PAGE: string = 'DB_PAGE';
  static readonly MEDIA_PAGE: string = 'MEDIA_PAGE';
  static readonly CUSTOMDIALOGANIMATION_PAGE: string = 'CUSTOMDIALOGANIMATION_PAGE';
  static readonly RENAMECUSTOMDIALOG_PAGE: string = 'RENAMECUSTOMDIALOG_PAGE';
  static readonly TABSATTR_PAGE: string = 'TABSATTR_PAGE';
  static readonly TABSANIMATION_PAGE: string = 'TABSANIMATION_PAGE';
  static readonly ASYNCHRONY_PAGE: string = 'ASYNCHRONY_PAGE';
  static readonly TIMEDEMO_PAGE: string = 'TIMEDEMO_PAGE';
  static readonly DATEDEMO_PAGE: string = 'DATEDEMO_PAGE';
  static readonly OPENCUSTOMDIALOG_PAGE: string = 'OPENCUSTOMDIALOG_PAGE';
  static readonly OPENCUSTOMDIALOGWITHANIMATOR_PAGE: string = 'OPENCUSTOMDIALOGWITHANIMATOR_PAGE';
  static readonly OPENCUSTOMDIALOGWITHANIMATOR_PAGE2: string = 'OPENCUSTOMDIALOGWITHANIMATOR_PAGE2';
  static readonly CEILING_PAGE: string = 'CEILING_PAGE';
  static readonly CAMERA_PAGE: string = 'CAMERA_PAGE';
  static readonly DAYINJIDEMO_PAGE: string = 'DAYINJIDEMO_PAGE';
  static readonly PROGRESS_TASK: string = 'PROGRESS_TASK';
}